[package]
authors.workspace      = true
description            = "Protobuf serialization of miden-client types"
edition.workspace      = true
license.workspace      = true
name                   = "miden-client-proto"
publish                = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lib]
crate-type = ["lib"]
doctest    = false

[dependencies]
# Miden dependencies
miden-client   = { workspace = true }
miden-objects  = { workspace = true }
miden-protocol = { workspace = true }

# Workspace dependencies
prost     = { features = ["derive", "std"], workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true

[build-dependencies]
miden-objects = { workspace = true }
prost-build   = { version = "0.14" }
protox        = { workspace = true }

[dev-dependencies]
miden-standards = { features = ["testing"], workspace = true }
